### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Psilogin** [skills/github-pages#60]
# **Descriptioin of the bug**

**Comment by CuiJinku** [comment]
If you have followed the tutorial and clicked the button "Start course", your repository is created with the "GitHub Pages" template. You can find the green button "Use this template" on the top right, next to "About". In this way, you will have a branch named 'my-pages' along with your 'main' branch.

<a href="https://github.com/skills/github-pages/generate"><img src="https://user-images.githubusercontent.com/1221423/218596841-0645fe1a-4aaf-4f51-9ab3-8aa2d3fdd487.svg" alt="start-course" style="max-width: 100%;"></a>


If you create your site repository from a scratch instead of using this template, there will not be a 'my-pages' branch.

**Comment by hectorsector** [comment]
Thank you @CuiJinku!
