### ISSUE TITLE
Tutorial is stuck on Step 4 - Does not proceed to step 5

### ISSUE THREAD

**Issue by 1dropaflame** [skills/github-pages#94]
### Discussed in https://github.com/orgs/skills/discussions/468

<div type='discussions-op-text'>

<sup>Originally posted by **CodaCodr** January 12, 2024</sup>
Hi

I'm working through the course to create a github blog. It worked fine until the end of step 4. I've waited ~5mins or more, refreshing does nothing.

How do I proceed?
</div>

**Comment by hectorsector** [comment]
Hello there! I've taken the course and verified it's working. I tried looking for your repository but I cannot see it, so it may be private or deleted since you opened this issue. Since I cannot reproduce the bug, I'll go ahead and close this issue but please open again if I'm misunderstanding. Thanks.

**Comment by 1dropaflame** [comment]
It is not fixed. see https://github.com/orgs/skills/discussions/468

**Comment by msaltenna** [comment]
still a problem in 2025 stuck on step #4

**Comment by kalenz86** [comment]
y

**Comment by gokidcbk** [comment]
almost like 6-7

**Comment by ira-ilchyshyn** [comment]
still an issue

**Comment by ira-ilchyshyn** [comment]
reproducible bug
Please reopen issue

**Comment by Hoooyo7878** [comment]
Asc Like fille isodira shp
